
CREATE TABLE LDC_PROGRAMADOR(PGIDENT	NUMBER(15) NOT NULL,
                            PGPRNOM	VARCHAR2(100) NOT NULL,
                            PGSENOM	VARCHAR2(100) ,
                            PGPRAPE	VARCHAR2(100) NOT NULL,
                            PGSEAPE	VARCHAR2(100) ,
                            PGEDAD	NUMBER(3),
                            PGANEXP	NUMBER(3),
                            PGSEXO	VARCHAR2(1),
                            PGUSUAR	VARCHAR2(100),
                            PGFEACT	DATE);
ALTER TABLE LDC_PROGRAMADOR ADD CONSTRAINT PK_LDC_PROGRAMADOR PRIMARY KEY(PGIDENT);
ALTER TABLE LDC_PROGRAMADOR ADD CONSTRAINT CK_PROGRAMADOR_SEXO CHECK (PGSEXO = 'M' OR  PGSEXO = 'F');
COMMENT ON COLUMN LDC_PROGRAMADOR.PGIDENT IS 'Identificador del programador';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGPRNOM IS 'Primer nombre';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGSENOM IS 'Segundo nombre';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGPRAPE IS 'Primer apellido';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGSEAPE IS 'Segundo apellido';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGEDAD IS 'Edad';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGANEXP IS 'Año de experiencia';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGSEXO IS 'Sexo [M – Masculino, F - Femenino]';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGUSUAR IS 'Usuario';
COMMENT ON COLUMN LDC_PROGRAMADOR.PGFEACT IS 'Fecha de Actualizacion';
COMMENT ON TABLE LDC_PROGRAMADOR IS 'Programadores';   
/
CREATE SEQUENCE SEQ_LDC_PROGRAMADOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/


CREATE TABLE LDC_LENGUPROG(LPIDENT	NUMBER(15) NOT NULL,
                            LPNOMBR	VARCHAR2(100) NOT NULL,
                            LPDESCR	VARCHAR2(100) NOT NULL,
                            LPESTAD	VARCHAR2(1) NOT NULL,
                            LPUSUAR	VARCHAR2(100),
                            LPFEACT	DATE);
ALTER TABLE LDC_LENGUPROG ADD CONSTRAINT PK_LDC_LENGUPROG PRIMARY KEY(LPIDENT);
ALTER TABLE LDC_LENGUPROG ADD CONSTRAINT CK_LENGUPROG_ESTADO CHECK (LPESTAD = 'A' OR  LPESTAD = 'I');
COMMENT ON COLUMN LDC_LENGUPROG.LPIDENT  IS 'Identificador de Lenguaje de programacion';
COMMENT ON COLUMN LDC_LENGUPROG.LPNOMBR  IS 'Nombre';
COMMENT ON COLUMN LDC_LENGUPROG.LPDESCR  IS 'Descripcion';
COMMENT ON COLUMN LDC_LENGUPROG.LPESTAD  IS 'Estado [A – Activo, I - Inactivo]';
COMMENT ON COLUMN LDC_LENGUPROG.LPUSUAR  IS 'Usuario';
COMMENT ON COLUMN LDC_LENGUPROG.LPFEACT  IS 'Fecha de Actualizacion';
COMMENT ON TABLE LDC_LENGUPROG IS 'Lenguajes de programacion';
/
CREATE SEQUENCE SEQ_LDC_LENGUPROG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

CREATE TABLE LDC_PROYECTO(PYIDENT	NUMBER(15) NOT NULL,
                            PYNOMBR	VARCHAR2(100) NOT NULL,
                            PYVALOR	NUMBER(15,2) ,
                            PYFEINI	DATE,
                            PYFEFIN	DATE,
                            PYCAPRO	NUMBER(5),  
                            PYLEPRO	NUMBER(15),
                            PYESTAD	VARCHAR2(1),
                            PYUSUAR	VARCHAR2(100),
                            PYFEACT	DATE);
ALTER TABLE LDC_PROYECTO ADD CONSTRAINT PK_LDC_PROYECTO PRIMARY KEY(PYIDENT);
ALTER TABLE LDC_PROYECTO ADD CONSTRAINT CK_PROYECTO_VALFECHA CHECK (PYFEINI < PYFEFIN);
ALTER TABLE LDC_PROYECTO ADD CONSTRAINT CK_PROYECTO_ESTADO CHECK (PYESTAD = 'V' OR  PYESTAD = 'T');
ALTER TABLE LDC_PROYECTO ADD CONSTRAINT FK_PROYECTO_LENGUPROG FOREIGN KEY (PYLEPRO) REFERENCES LDC_LENGUPROG(LPIDENT);
COMMENT ON COLUMN LDC_PROYECTO.PYIDENT IS 'Identificador de proyecto';
COMMENT ON COLUMN LDC_PROYECTO.PYNOMBR IS 'Nombre del proyecto';
COMMENT ON COLUMN LDC_PROYECTO.PYVALOR IS 'Valor del proyecto';
COMMENT ON COLUMN LDC_PROYECTO.PYFEINI IS 'Fecha de inicio';
COMMENT ON COLUMN LDC_PROYECTO.PYFEFIN IS 'Fecha de finalizacion';
COMMENT ON COLUMN LDC_PROYECTO.PYCAPRO IS 'Cantidad de programadores';
COMMENT ON COLUMN LDC_PROYECTO.PYLEPRO IS 'Lenguaje de programacion';
COMMENT ON COLUMN LDC_PROYECTO.PYESTAD IS 'Estado [V – Vigente, T - Terminado]';
COMMENT ON COLUMN LDC_PROYECTO.PYUSUAR IS 'Usuario';
COMMENT ON COLUMN LDC_PROYECTO.PYFEACT IS 'Fecha de Actualizacion';
COMMENT ON TABLE LDC_PROYECTO IS 'Proyectos';
/
CREATE SEQUENCE SEQ_LDC_PROYECTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

CREATE TABLE LDC_PROGLEGPRO(PLPPROGR	NUMBER(15) NOT NULL,
							PLPLENGU	NUMBER(15) NOT NULL,
                            PLPUSUAR	VARCHAR2(100),
                            PLPFEACT	DATE);
ALTER TABLE LDC_PROGLEGPRO ADD CONSTRAINT PK_LDC_PROGLEGPRO PRIMARY KEY(PLPPROGR, PLPLENGU);
ALTER TABLE LDC_PROGLEGPRO ADD CONSTRAINT FK_PROGLEGPRO_PROGRAMADOR FOREIGN KEY (PLPPROGR) REFERENCES LDC_PROGRAMADOR(PGIDENT);
ALTER TABLE LDC_PROGLEGPRO ADD CONSTRAINT FK_PROGLEGPRO_LENGUPROG FOREIGN KEY (PLPLENGU) REFERENCES LDC_LENGUPROG(LPIDENT);
COMMENT ON COLUMN LDC_PROGLEGPRO.PLPPROGR  IS 'Identificador del programador';
COMMENT ON COLUMN LDC_PROGLEGPRO.PLPLENGU  IS 'Identificador del lenguaje de programacion';
COMMENT ON COLUMN LDC_PROGLEGPRO.PLPUSUAR  IS 'Usuario';
COMMENT ON COLUMN LDC_PROGLEGPRO.PLPFEACT  IS 'Fecha de Actualizacion';
COMMENT ON TABLE LDC_PROGLEGPRO IS 'Programadores [N - N] Lenguajes de programacion';
/
ALTER TABLE LDC_PROGLEGPRO ADD PLPPUNEX NUMBER(3);
COMMENT ON COLUMN LDC_PROGLEGPRO.PLPPUNEX IS 'Punto de experiencia';
/

CREATE TABLE LDC_PROGPROYECTO (PPPROGR	NUMBER(15) NOT NULL,
                            PPPROYE	NUMBER(15) NOT NULL,
                            PPUSUAR	VARCHAR2(100),
                            PPFEACT	DATE);
ALTER TABLE LDC_PROGPROYECTO ADD CONSTRAINT PK_LDC_PROGPROYECTO PRIMARY KEY(PPPROGR, PPPROYE);
ALTER TABLE LDC_PROGPROYECTO ADD CONSTRAINT FK_PROGPROYECTO_PROGRAMADOR FOREIGN KEY (PPPROGR) REFERENCES LDC_PROGRAMADOR(PGIDENT);
ALTER TABLE LDC_PROGPROYECTO ADD CONSTRAINT FK_PROGPROYECTO_PROYECTO FOREIGN KEY (PPPROYE) REFERENCES LDC_PROYECTO(PYIDENT);
COMMENT ON COLUMN LDC_PROGPROYECTO.PPPROGR  IS 'Identificador del programador';
COMMENT ON COLUMN LDC_PROGPROYECTO.PPPROYE  IS 'Identificador del proyecto';
COMMENT ON COLUMN LDC_PROGPROYECTO.PPUSUAR  IS 'Usuario';
COMMENT ON COLUMN LDC_PROGPROYECTO.PPFEACT  IS 'Fecha de Actualizacion';
COMMENT ON TABLE LDC_PROGPROYECTO IS 'Programadores [N - N] Proyecto';
/


