
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Josh', 'Glen', 'Brito', 'Avila', 30, 8, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Ana', 'María', 'López', 'Rodríguez', 28, 5, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Luis', 'Fernando', 'Martínez', 'Sánchez', 35, 12, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Gabriela', 'Sofía', 'Ramírez', 'Hernández', 26, 4, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Javier', 'Eduardo', 'González', 'Díaz', 40, 15, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Paula', 'Andrea', 'Fernández', 'Ruiz', 32, 9, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Ricardo', 'Emilio', 'Torres', 'Vargas', 29, 6, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Valeria', 'Isabel', 'Castro', 'Mendoza', 31, 10, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Fernando', 'José', 'Morales', 'Ortega', 27, 3, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Camila', 'Lucía', 'Guzmán', 'Peña', 33, 11, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Alejandro', 'Daniel', 'Rojas', 'Cabrera', 36, 13, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Jessica', 'Estefanía', 'Salazar', 'Jiménez', 25, 2, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Diego', 'Antonio', 'Navarro', 'Silva', 34, 14, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Lorena', 'Patricia', 'Molina', 'Herrera', 29, 7, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Oscar', 'Manuel', 'Cárdenas', 'Reyes', 38, 16, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Diana', 'Beatriz', 'Pacheco', 'Soto', 30, 8, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Mario', 'Armando', 'Aguilar', 'Cruz', 26, 5, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Verónica', 'Carolina', 'Suárez', 'Flores', 28, 6, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Esteban', 'Roberto', 'Méndez', 'Ríos', 31, 10, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Natalia', 'Fernanda', 'Delgado', 'Acosta', 27, 4, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Francisco', 'Luis', 'Peralta', 'Velásquez', 35, 12, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Adriana', 'Susana', 'Campos', 'Barrera', 24, 1, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Jorge', 'Alberto', 'Vera', 'Escobar', 39, 17, 'M');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Cecilia', 'Angélica', 'Bravo', 'Fuentes', 32, 9, 'F');
INSERT INTO LDC_PROGRAMADOR (PGPRNOM, PGSENOM, PGPRAPE, PGSEAPE, PGEDAD, PGANEXP, PGSEXO) VALUES ('Rodrigo', 'Hernán', 'Paredes', 'Mejía', 37, 14, 'M');

commit;
/

INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Python', 'Lenguaje interpretado y multipropósito, popular en desarrollo web, IA y ciencia de datos.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('JavaScript', 'Lenguaje de scripting usado principalmente para desarrollo web en frontend y backend.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Java', 'Lenguaje orientado a objetos ampliamente usado en aplicaciones empresariales y móviles.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('C#', 'Lenguaje de programación desarrollado por Microsoft.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('C++', 'Lenguaje de programación de alto rendimiento, utilizado en sistemas operativos y software embebido.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('PHP', 'Lenguaje de programación ampliamente usado en el desarrollo web para el backend.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Ruby', 'Lenguaje interpretado conocido por su facilidad de uso y su framework Ruby on Rails.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Swift', 'Lenguaje de programación desarrollado por Apple para aplicaciones en iOS y macOS.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Kotlin', 'Lenguaje moderno y conciso compatible con la JVM, recomendado para desarrollo Android.', 'A');
INSERT INTO LDC_LENGUPROG (LPNOMBR, LPDESCR, LPESTAD) VALUES ('Perl', 'Lenguaje de scripting utilizado en administración de sistemas y procesamiento de texto.', 'I');


commit;
/


INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('DevXpert', 50000, TO_DATE('2022-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 5, 1, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('CodeWave', 75000, TO_DATE('2021-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 4, 2, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('PixelForge', 60000, TO_DATE('2016-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 8, 3, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('WebNova', 90000, TO_DATE('2024-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 3, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('FastDeploy', 120000, TO_DATE('2024-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 1, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('TaskFlow API', 45000, TO_DATE('2024-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 7, 4, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('AuthShield', 85000, TO_DATE('2023-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 5, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('DataPulse', 95000, TO_DATE('2023-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 6, 6, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('AI Nexus', 150000, TO_DATE('2022-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 7, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('ByteSync', 110000, TO_DATE('2022-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 4, 7, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('VisionBoard', 70000, TO_DATE('2022-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 9, 8, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('ConnectHub', 80000, TO_DATE('2025-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 9, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('ShopEase', 130000, TO_DATE('2025-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 6, 4, 'V');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYFEFIN, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('TrackIt', 55000, TO_DATE('2021-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), SYSDATE, 5, 10, 'T');
INSERT INTO LDC_PROYECTO (PYNOMBR, PYVALOR, PYFEINI, PYFEFIN, PYCAPRO, PYLEPRO, PYESTAD) VALUES ('FormGenie', 40000, TO_DATE('2021-01-31 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), SYSDATE, 3, 6, 'T');
        
commit
/



